# Generated by Django 3.0.11 on 2021-02-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatting',
            old_name='content',
            new_name='message',
        ),
    ]
