# Generated by Django 3.0.11 on 2021-02-22 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendapplylist',
            name='userTo',
            field=models.ManyToManyField(related_name='appplyUserTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
