# Generated by Django 3.0.11 on 2021-02-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20210222_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendapplylist',
            name='userFrom',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendlist',
            name='userFrom',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
