# Generated by Django 3.0.11 on 2021-03-02 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0004_auto_20210302_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='userFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myFriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
