# Generated by Django 3.0.11 on 2021-01-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20210113_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandate',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='plans.Plan'),
        ),
    ]
