# Generated by Django 3.0.11 on 2021-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20210114_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='location',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
