# Generated by Django 3.0.11 on 2021-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20210114_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='areacode',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
