# Generated by Django 3.0.11 on 2021-01-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_areacode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_turn', models.CharField(max_length=10)),
                ('detail_img', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=20)),
                ('place_location', models.CharField(max_length=100)),
                ('place_x', models.CharField(max_length=100)),
                ('place_y', models.CharField(max_length=100)),
                ('place_memo', models.TextField()),
                ('plan_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailPlace', to='plans.PlanDate')),
            ],
        ),
    ]
