# Generated by Django 3.0.11 on 2021-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20210125_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailplan',
            name='place_memo',
            field=models.TextField(default=''),
        ),
    ]
