# Generated by Django 3.0.11 on 2021-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20210127_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailplan',
            name='place_memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
