# Generated by Django 3.0.11 on 2021-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_auto_20210206_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailplan',
            name='move_turn',
            field=models.IntegerField(),
        ),
    ]
