# Generated by Django 3.0.11 on 2021-03-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_planmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmember',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='plans.Plan'),
        ),
    ]
