# Generated by Django 3.0.11 on 2021-03-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0019_auto_20210302_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmember',
            name='complete',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
