# Generated by Django 3.0.11 on 2021-03-03 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0020_planmember_complete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planmember',
            unique_together={('plan', 'user')},
        ),
    ]
