# Generated by Django 3.0.11 on 2021-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_auto_20210303_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailplan',
            name='place_type',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
    ]
