# Generated by Django 3.0.11 on 2021-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_detailplan_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailplan',
            name='house_id',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
