# Generated by Django 3.0.11 on 2021-03-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0024_planrejectreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=30)),
                ('recommend', models.IntegerField(blank=True, default=0)),
                ('share', models.IntegerField(blank=True, default=0)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('areacode', models.CharField(blank=True, max_length=2)),
                ('range_date', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_createUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharePlanDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth_day', models.CharField(max_length=2)),
                ('share_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_schedule', to='plans.SharePlan')),
            ],
            options={
                'ordering': ['nth_day'],
            },
        ),
        migrations.CreateModel(
            name='ShareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_turn', models.IntegerField()),
                ('detail_img', models.CharField(max_length=200)),
                ('place_name', models.CharField(max_length=20)),
                ('place_location', models.CharField(max_length=100)),
                ('place_x', models.CharField(max_length=100)),
                ('place_y', models.CharField(max_length=100)),
                ('place_type', models.CharField(blank=True, default='0', max_length=1)),
                ('house_id', models.CharField(blank=True, default='0', max_length=10)),
                ('share_plan_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_detailPlace', to='plans.SharePlanDate')),
            ],
            options={
                'ordering': ['move_turn'],
            },
        ),
    ]
