# Generated by Django 3.0.11 on 2021-03-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0025_sharedetail_shareplan_shareplandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareplan',
            name='plan',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paln_share', to='plans.Plan'),
            preserve_default=False,
        ),
    ]
