# Generated by Django 3.0.11 on 2021-03-19 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0026_shareplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareplan',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paln_share', to='plans.Plan'),
        ),
    ]
