# Generated by Django 3.0.11 on 2021-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0027_auto_20210319_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailplan',
            name='reservation_id',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
