# Generated by Django 3.0.11 on 2021-03-23 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0030_auto_20210324_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_paln_score', to='plans.SharePlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_score_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
