# Generated by Django 3.0.11 on 2021-03-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0032_sharescore_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedetail',
            name='reservation_id',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
    ]
