# Generated by Django 3.0.11 on 2020-12-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRegist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseName', models.CharField(max_length=20)),
                ('houseAddress', models.CharField(max_length=40)),
                ('houseDetailAddress', models.CharField(max_length=30)),
                ('housePrice', models.CharField(max_length=10)),
                ('houseType', models.CharField(max_length=10)),
                ('maxPerson', models.CharField(max_length=10)),
                ('rooms', models.CharField(max_length=2)),
                ('xPoint', models.CharField(max_length=50)),
                ('yPoint', models.CharField(max_length=50)),
                ('mainImage', models.ImageField(upload_to='house/main/%Y/%m/%d')),
                ('endDate', models.CharField(max_length=20)),
                ('startDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailImage', models.ImageField(upload_to='house/detail/%Y/%m/%d')),
                ('houseRegist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.HouseRegist')),
            ],
        ),
    ]
