# Generated by Django 3.0.11 on 2020-12-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseregist',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
