# Generated by Django 3.0.11 on 2021-01-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_houseregist_houseid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseDetailImage',
            new_name='HousedetaiiImage',
        ),
        migrations.AlterField(
            model_name='housedetaiiimage',
            name='houseRegist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Houseregist'),
        ),
    ]
